# Generated by Django 6.0.5 on 2026-07-21 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_comment_moderated_at_comment_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Перегляди'),
        ),
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Оцінка')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.post', verbose_name='Стаття')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Оцінка статті',
                'verbose_name_plural': 'Оцінки статей',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='unique_post_rating_per_user'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='post_rating_score_between_1_and_5')],
            },
        ),
    ]
