# Generated by Django 6.0.5 on 2026-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Текст')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='medium', max_length=20, verbose_name='Пріоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ('-created_at',),
            },
        ),
    ]
