# Generated by Django 6.0.5 on 2026-07-02 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Тривалість у днях')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('canceled', 'Скасована'), ('expired', 'Завершена')], default='active', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Підписка',
                'verbose_name_plural': 'Підписки',
                'ordering': ('-start_date',),
            },
        ),
    ]
